### PR TITLE
[9] Implement `JsonPath` for holding parsed JSON Path queries

### LINKED ISSUE #9: Pre-Parsed JsonPath newtype
I think a new type like `struct JsonPath(_)` would make sense to be included.

The `JsonPath` type should be pre-parsed and validated and never raise an error when passed to `.json_path()`. It could also implement `Deserialize` (e.g. for use in config files).

This would also allow further optimization, since the path wouldn't need to be re-parsed everytime it is used.

It would be nice if `.json_path()` would become infallibale if passed a `JsonPath` but that would mean a breaking change, otherwise something like `fn json_path<T>(path: T) where T: TryInto<JsonPath>, crate::Error: From<T::Error>` could work (maybe tricky to accept &JsonPath).

My current workaround for the config usecase:

```rs
#[derive(Debug)]
pub struct JsonPath(String);

impl std::ops::Deref for JsonPath {
    type Target = str;

    fn deref(&self) -> &Self::Target {
        self.0.as_str()
    }
}

impl std::fmt::Display for JsonPath {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.0)
    }
}

impl<'de> Deserialize<'de> for JsonPath {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let inner = String::deserialize(deserializer)?;
        serde_json::Value::Null
            .json_path(&inner)
            .map_err(serde::de::Error::custom)?;
        Ok(JsonPath(inner))
    }
}
```

### PR DESCRIPTION
**Pull request by hiltontj**
The JsonPath struct was introduced, which holds a parsed, valid JSON Path query. This can be used to query `serde_json::Value`s. For example:
```rust
let value = json!({ "foo": { "bar": ["baz", "bop"] } });
let path = JsonPath::parse("$.foo.bar.*")?; // <- Note, this is fallible
let nodes = path.query(&value).all();       // <- while this is not
assert_eq!(nodes, vec!["baz", "bop"]);
```
The `JsonPath` type can be used to parse JSON Path query strings only once, and then re-use the parsed query. This separates the fallible step (the parsing) from the infallible step (the querying), which will be a quality of life improvement for the reasons discussed in #9.

In addition, `FromStr` and `Deserialize` implementions were included for the `JsonPath` type. This will allow the type to be used directly where `Deserialize` is used.

The docs and tests were updated to reflect the new API.

This would be a breaking change, so will require a bump to `0.5.x`.

This aims to close #9 .

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -175,17 +183,140 @@
...
+            }
+
+            fn visit_str<E>(self, v: &str) -> Result<Self::Value, E>
+            where
+                E: serde::de::Error,
+            {
+                JsonPath::parse(v).map_err(serde::de::Error::custom)
+            }
+
+            fn visit_borrowed_str<E>(self, v: &'de str) -> Result<Self::Value, E>
```
Comment (Dav1dde) [inline src/lib.rs:293]: I think it is enough if you only implement `visit_str`, that's what [`url::Url`](https://github.com/servo/rust-url/blob/10929606359afa54e363ef7ebf311f106247f5d9/url/src/lib.rs#L2727-L2756) is doing.

File: src/lib.rs [hunk 2]
```diff
@@ -175,17 +183,140 @@
...
+    where
+        D: serde::Deserializer<'de>
+    {
+        struct JsonPathVisitor(PhantomData<JsonPath>);
+
+        impl<'de> Visitor<'de> for JsonPathVisitor {
+            type Value = JsonPath;
+
+            fn expecting(&self, formatter: &mut std::fmt::Formatter) -> std::fmt::Result {
+                write!(formatter, "a string")
```
Comment (Dav1dde) [inline src/lib.rs:283]: message should be something like "a string representing a valid JSONPath expression"

File: src/lib.rs [hunk 3]
```diff
@@ -175,17 +183,140 @@
...
+/// # fn main() {
+/// # let path = JsonPath::parse("$.foo.*").expect("valid JSON Path");
+/// let value = json!({"foo": [1, 2, 3, 4]});
+/// let nodes = path.query(&value);
+/// # assert_eq!(nodes.all(), vec![1, 2, 3, 4]);
+/// # }
+/// ```
+/// 
+/// [jp_spec]: https://www.ietf.org/archive/id/draft-ietf-jsonpath-base-10.html
+pub struct JsonPath(Query);
```
Comment (Dav1dde) [inline src/lib.rs:226]: This should probably implement at least `Debug`
